### ISSUE TITLE
Child component's ready method not called

### ISSUE THREAD

**Issue by pperez** [jayway/vue-js-workshop#10]
I've been trying to add client side validation (key to perfection on update products), it seems to work, but when it needs to reset the formError data it doesn't do it.
I've added a console.log to the ready method but i don't see it get executed:

~~~
<script>
export default {
  props: ['product'],
  data() {
    return {
      formErrors: {}
    }
  },
  ready() {
    console.log('calling ready method from child component');
    this.$watch('product.id', () => {
      this.formErrors = {};
    })
  },
[...]
~~~

I guess i could add the watcher as a watch method on the component, but i'm curious on why the ready method is not getting executed ...
I tried the code on ```exercise-files/remove-products``` but it doesn't work either :(

**Comment by marcuslindfeldt** [comment]
Fixed in f7d3597. The ready() method was renamed created() in Vue 2
