### ISSUE TITLE
Navbar icon and card items not visible in demo

### ISSUE THREAD

**Issue by theno** [jayway/vue-js-workshop#13]
Running the demo, the navbar icon is not visible and the navigation items cannot be shown.

As a workaround it works if `hidden-sm-up` is removed from the value of the `button`'s `class` attribute in file `AppNav.vue`.

Also, added product items cannot be "dropped out" from the navigation (don't know a workaround for this).

**Comment by marcuslindfeldt** [comment]
Fixed in 1e177bb81e2148b3016ed868262f7db7d2cfccee Bootstrap 4 changed their API's significantly between alpha versions.
