### ISSUE TITLE
Bahasa Indonesia Version

### ISSUE THREAD

**Issue by tamatamvan** [jayway/vue-js-workshop#17]
Hello, I'm Tama from Indonesia, first of all I would like to thank you for your workshop. It's so good and really easy to understand. I often recommending this  workshop to my colleagues who are willing to learn vue.js.

Now, I'm gonna make a Vue.js workshop in my native language, and if you don't mind, I would like to use your vue.js workshop as my references. Thanks

**Comment by marcuslindfeldt** [comment]
Hi Tama,

Thank you for your kind words. Of course you can use the workshop as a reference! I'm just happy that people find it useful.

Regards,
Marcus
