### ISSUE TITLE
demo failed / popper is missing

### ISSUE THREAD

**Issue by ludoo0d0a** [jayway/vue-js-workshop#18]
After build and run the demo, I receive this error : 

> Bootstrap dropdown require Popper.js

It seems bootstrap is uisng now popper and it needs to be explictly referenced.
I tried to include it but not sure how.
thx for the help !

**Comment by marcuslindfeldt** [comment]
Thanks for letting me know! Fixed in 1e177bb81e2148b3016ed868262f7db7d2cfccee
