### ISSUE TITLE
Crash on "npm run dev"

### ISSUE THREAD

**Issue by Surfoo** [jayway/vue-js-workshop#19]
I tried the workshop, and when I run `npm run dev` from https://jayway.github.io/vue-js-workshop/docs/list-products.html, I have this error:

[error.txt](https://github.com/jayway/vue-js-workshop/files/1282501/error.txt)

**Comment by marcuslindfeldt** [comment]
I am unable to reproduce the problem with node v8.4.0 and npm v 5.4.0. Did you remember to run `npm install` from the `/list-products` directory? Does it still happen after you remove the `/node_modules` directory and run `npm install` again?

**Comment by Surfoo** [comment]
hum, I tried on a other computer and it works... I'll try from scratch on the other one.. Thanks!
