### ISSUE TITLE
Reporting a few potential issues

### ISSUE THREAD

**Issue by coisnepe** [jayway/vue-js-workshop#3]
Hey jayway,

Going through your -awesome- tutorial, and have run into a few issues. 

- it's pretty obvious, but in _Add products_ I don't think you mention that _App.vue_ should be updated to get _ManageProducts_ instead of _ProductList_ that we initially used.

- for some reason it couldn't find the uuid package, though I'm pretty sure I ran `npm install` in all the relevant folders. I quit the server, installed it manually (`npm install uuid`) and restarted the server.

- I get a `Duplicate declaration "product"` error. After I changed `const product` to `const products` I could add products as expected.

```
BabelLoaderError: Duplicate declaration "product"

  60 |     onFormSave(product) {
  61 |       // clone the productInForm object
> 62 |       const product = {
```
I'm completely new to node, VueJS and SPAs, but I hope these comments are constructive/helpful!

Thanks for putting together this tutorial 👍 !

**Comment by marcuslindfeldt** [comment]
@coisnepe Thank you for your feedback!

Regarding the ManageProducts component I left it as an exercise for the reader. It's mentioned in the key to perfection section [here](https://jayway.github.io/vue-js-workshop/docs/list-products.html) but maybe we should make it more clear.

About the uuid package it's in the `package.json` in the `/create-products` exercise files. I guess that you started of from the `/list-products` folder and continued on from that?

**Comment by coisnepe** [comment]
@marcuslindfeldt This might be why... JS noob... I'd warned you. Well I really enjoy it anyway, starred and subscribed. Thank you!

**Comment by marcuslindfeldt** [comment]
I corrected the "Duplicate declaration" error so I'm closing this issue for now but I will think about rewriting some parts of the workshop to make it possible to follow the whole workshop from start to finish without having to jump to the different `/exercise-files` folders.

**Comment by FerchoCarcho** [comment]
Excellent tutorial when migrating to vuex, and overall..
